
CREATE DATABASE IF NOT EXISTS live_tv;
USE live_tv;

CREATE TABLE IF NOT EXISTS channels (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  logo VARCHAR(255),
  link VARCHAR(255),
  category VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255)
);
